# codemagic.yaml - iOS Debug Build Configuration
workflows:
  ios-debug:
    name: iOS Debug Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - manual  # Allow manual trigger
      branch_patterns:
        - pattern: '*'  # Build from any branch
          include: true
    scripts:
      - name: Set up debug signing
        script: |
          # Use automatic signing for debug builds
          sed -i '' 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = "";/' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_STYLE = Manual/CODE_SIGN_STYLE = Automatic/' ios/Runner.xcodeproj/project.pbxproj
          
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Install CocoaPods
        script: |
          cd ios && pod install
          
      - name: Build iOS Debug
        script: |
          # Build debug version (faster, includes debug symbols)
          flutter build ios --debug --no-codesign
          
      - name: Create Debug IPA
        script: |
          # Create IPA for distribution
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Debug \
            -destination generic/platform=iOS \
            -archivePath Runner.xcarchive \
            archive
            
          xcodebuild -exportArchive \
            -archivePath Runner.xcarchive \
            -exportPath ../build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/Runner.app
      - ios/Runner.xcarchive
      
    publishing:
      email:
        recipients:
          - your-email@example.com  # Get notified when build completes
        notify:
          success: true
          failure: true