# codemagic.yaml - Fixed version to match your local setup
workflows:
  ios-debug-build:
    name: iOS Debug Build
    environment:
      flutter: 3.16.9  # ✅ FIXED: Match your local Flutter version
      xcode: 15.2      # Use slightly older Xcode for compatibility
      cocoapods: default
    triggering:
      events:
        - push
        - manual
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Show environment versions
        script: |
          echo "Flutter version:"
          flutter --version
          echo "Dart version:"
          dart --version
          echo "Xcode version:"
          xcodebuild -version
          
      - name: Clean and get dependencies
        script: |
          # Clean any cached builds
          flutter clean
          
          # Remove pubspec.lock to force fresh resolution
          rm -f pubspec.lock
          
          # Get dependencies with verbose output
          flutter pub get --verbose
          
      - name: Verify dependencies
        script: |
          # Show what got resolved
          flutter pub deps
          
      - name: Install iOS dependencies
        script: |
          cd ios
          # Clean CocoaPods cache
          pod cache clean --all
          # Install with repo update
          pod install --repo-update --verbose
          
      - name: Build iOS Debug
        script: |
          # Build with verbose output for debugging
          flutter build ios --debug --no-codesign --verbose
          
      - name: List build artifacts
        script: |
          echo "Build artifacts:"
          ls -la build/ios/
          echo "iOS build contents:"
          ls -la build/ios/Runner.app/ || echo "Runner.app not found"
          
    artifacts:
      - build/ios/Runner.app
      - build/ios/iphoneos/Runner.app
      
    publishing:
      email:
        recipients:
          - your-email@example.com  # Replace with your email
        notify:
          success: true
          failure: true