# codemagic.yaml - Compatible with Flutter 3.16.x / Dart 3.2.6
workflows:
  ios-debug-build:
    name: iOS Debug Build
    environment:
      flutter: 3.16.9  # Specify compatible Flutter version
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - manual
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Show versions
        script: |
          flutter --version
          dart --version
          
      - name: Get dependencies
        script: |
          # Clean previous builds
          flutter clean
          
          # Get dependencies (should work with compatible versions)
          flutter pub get
          
          # Verify no conflicts
          flutter pub deps
          
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          
      - name: Build iOS Debug
        script: |
          # Build debug version
          flutter build ios --debug --no-codesign --verbose
          
    artifacts:
      - build/ios/Runner.app
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true