workflows:
  ios-debug-only:
    name: iOS Debug Build Only
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: 3.19.0
      xcode: 15.2
      cocoapods: default
    triggering:
      events:
        - push
        - manual
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Show environment versions
        script: |
          echo "=== BUILDING iOS ONLY - NO ANDROID ==="
          echo "Flutter version:"
          flutter --version
          echo "Xcode version:"
          xcodebuild -version
          
      - name: Clean and get dependencies
        script: |
          flutter clean
          rm -f pubspec.lock
          flutter pub get --verbose
          
      - name: Install iOS dependencies
        script: |
          cd ios
          pod cache clean --all
          pod install --repo-update --verbose
          
      - name: Build iOS Debug ONLY (No Android)
        script: |
          echo "=== BUILDING iOS DEBUG - SKIPPING ANDROID ==="
          flutter build ios --debug --no-codesign --verbose
          
      - name: List iOS build artifacts
        script: |
          echo "iOS build artifacts:"
          ls -la build/ios/
          find build/ios/ -name "*.app" -type d
          
    artifacts:
      - build/ios/Runner.app
      - build/ios/**/*.app
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true