name: vaccigo
description: "A vaccination tracking app with AI-powered scanning"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # HTTP requests
  http: ^1.2.0
  
  # Camera and image handling
  camera: ^0.10.6
  image_picker: ^1.0.8
  
  # Permissions
  permission_handler: ^11.3.1
  
  # File system
  path_provider: ^2.1.4
  
  # Machine Learning - Updated version
  google_ml_kit: ^0.17.0
  
  # Security
  crypto: ^3.0.3
  
  # Utilities
  collection: ^1.18.0
  meta: ^1.10.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_lints: ^2.0.3

# Fix plugin compatibility issues
dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.20

flutter:
  uses-material-design: true

  # Assets (commented out until directories exist)
  # Uncomment and create directories when you have assets to include
  # assets:
  #   - assets/images/
  #   - assets/logos/
  #   - assets/icons/

  # Fonts (optional - uncomment if you have custom fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700