name: vaccigo
description: "A vaccination tracking app with AI-powered scanning"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ADD THIS: For date picker localization
  flutter_localizations:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.6
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # HTTP requests
  http: ^1.2.0
  
  # Camera and image handling
  camera: ^0.10.6
  image_picker: ^1.0.8
  
  # Permissions
  permission_handler: ^11.3.1
  
  # File system
  path_provider: ^2.1.4
  
  # Machine Learning
  google_ml_kit: ^0.16.3
  
  # Security
  crypto: ^3.0.3
  
  # ADD THESE: Missing utilities causing some issues
  collection: ^1.17.1
  meta: ^1.9.1
  intl: ^0.18.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  
  # Linting
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/

  # Fonts (optional - uncomment if you have custom fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700